# Travis CI

language: php
dist: trusty
sudo: false
php:
- 7.2

before_script:
- cd /home/travis/build/
- echo | pecl install channel://pecl.php.net/yaml-2.0.2

- git clone https://github.com/krakjoe/pthreads.git
- cd pthreads
- git checkout 6c6b15138c923b69cfa46ee05fc2dd45da587287
- phpize
- ./configure
- make
- make install
- cd ..
- echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

- git clone --recursive https://github.com/pmmp/PocketMine-MP.git
- mkdir -p PocketMine-MP/plugins/BlockSniper

- cd PocketMine-MP/plugins/
- wget -O DevTools.phar https://poggit.pmmp.io/r/18384/PocketMine-DevTools.phar
- cd /home/travis/build/

- cp -rf BlockHorizons/BlockSniper/src PocketMine-MP/plugins/BlockSniper
- cp -rf BlockHorizons/BlockSniper/resources PocketMine-MP/plugins/BlockSniper
- cp -rf BlockHorizons/BlockSniper/plugin.yml PocketMine-MP/plugins/BlockSniper
- cp -rf BlockHorizons/BlockSniper/LICENSE PocketMine-MP/plugins/BlockSniper
- cp -rf BlockHorizons/BlockSniper/travis.php PocketMine-MP/plugins/BlockSniper

- cp -rf BlockHorizons/BlockSniper/tests PocketMine-MP/plugins/

- cd PocketMine-MP/
- composer install

script:
- php plugins/BlockSniper/travis.php

notifications:
  email:
    on_failure: always
    on_success: never